/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: tab1bit0 (https://sketchfab.com/tab1bit0)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ufo-8288a85fdf9d48f6a9a9ec6df27d5aa0
title: ufo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ufo2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} position={[0,0,4]}>
          <group rotation={[0, 0, -Math.PI]} scale={[-1.6, 0.38, 1.6]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Dome.belt']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Bottom} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Glass.mini']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Bottom.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ufo2.gltf')
