/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MAD_DUDE (https://sketchfab.com/MAD_DUDE)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ufospaceship-77a99a30b7eb42a3b7017dd97e5885b1
title: ufo(spaceship)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ufo.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.08, -0.05]} rotation={[-1.57, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-0.41, 0.8, -0.07]} scale={3.58}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.big_light} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.big_light} />
            <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.glass} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.light} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.004']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ufo.gltf')
